name: heli
channels: 
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - descartes
  - shapely
  - contextily
  - gdal
  - python-pdal
  - scipy
  - haversine
  - utm
  - bokeh
  - panel
  - holoviews
  - geoviews
  - seaborn
  - rasterstats
  - hvplot
  - rasterio
  - xarray
  - s3fs
  - laspy
  - pip
  - pip:
    - open3d